### ISSUE TITLE
PowerSag

### ISSUE THREAD

**Issue by fpesari** [hannesbraun/airwindows-lv2#7]
Hello,

somebody on Linuxmusicians mentioned PowerSag as a useful plugin. Could you please port it? Thank you!

**Comment by hannesbraun** [comment]
PowerSag was ported with 1680ebbf9ce167d5841d67be2a940942668193ff. My PowerSag2 port still has some issues. I'll see when I have the time to fix them and commit the port.

**Comment by fpesari** [comment]
> PowerSag was ported with [1680ebb](https://github.com/hannesbraun/airwindows-lv2/commit/1680ebbf9ce167d5841d67be2a940942668193ff). My PowerSag2 port still has some issues. I'll see when I have the time to fix them and commit the port.

No rush, thank you for your work, as always :smile:

**Comment by hannesbraun** [comment]
And PowerSag2 is here as well (97e80a06b5d8827567c69fe81939754d41d7c23d).

> My PowerSag2 port still has some issues.

Turns out the MacVST I was testing against doesn't null with itself either. Sometimes, one of both channels cranks out a signal during the null test for something like half a second (looking at the code, I'd probably say 16386 samples). So, as this behavior seems to be kind of expected, I didn't dig deeper into the code. I think this is fine.
